tests/ui/async-await/issue-70818.rs
===================================

Last edited: 2023-03-30 20:35:59

Contents:

.. code-block:: rs

    // edition:2018

use std::future::Future;
fn foo<T: Send, U>(ty: T, ty1: U) -> impl Future<Output = (T, U)> + Send {
    //~^ Error future cannot be sent between threads safely
    async { (ty, ty1) }
}

fn main() {}


