compiler/rustc_error_codes/src/error_codes/E0580.md
===================================================

Last edited: 2023-03-30 20:35:59

Contents:

.. code-block:: md

    The `main` function was incorrectly declared.

Erroneous code example:

```compile_fail,E0580
fn main(x: i32) { // error: main function has wrong type
    println!("{}", x);
}
```

The `main` function prototype should never take arguments.
Example:

```
fn main() {
    // your code
}
```

If you want to get command-line arguments, use `std::env::args`. To exit with a
specified exit code, use `std::process::exit`.


